[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "node scripts/copy-frontend.js"
]

[start]
cmd = "cd backend && npx prisma generate && node server.js"

[variables]
NODE_ENV = "production"
